#include "../include/data_generation.h"

#define BAD_IP_SIZE        22
#define MAX_IP_BUFFER_SIZE 17 // xxx.xxx.xxx.xxx = 15 chars + \n + \0
#define MAX_OPTIONS        3

static uint32_t get_random_ip( void );
static uint64_t get_random_mac( void );
static void get_ip_to_hex( void );

/**
 * Array of bad IP addresses. These are addresses
 * that cannot be generated by our function.
 */
static const uint32_t BAD_IP[BAD_IP_SIZE] = {
    0,          0x10000000, 0x64400000, 0x7f000000, 0xa9fe0000, 0xac100000, 0xc0000000, 0xc0000008,
    0xc0000009, 0xc00000aa, 0xc00000ab, 0xc0000200, 0xc01fc400, 0xc034c100, 0xc0586300, 0xc0a80000,
    0xc0af3000, 0xc6120000, 0xc6336400, 0xcb007100, 0xf0000000, 0xffffffff };

/**
 * Calls other helper methods.
 *
 * @param void.
 *
 * @return void.
 */
void
compute_data( void ) {
  printf( "1. Generate random IP." );
  printf( "\n2. Generate random MAC." );
  printf( "\n3. Convert String IP to Hex:" );
  printf( "\nChoose an option to generate: " );
  int32_t option = -1;
  scanf( "%d", &option );

  while ( option < 1 || option > MAX_OPTIONS ) {
    printf( "\nThis is an invalid option. Try again: " );
    scanf( "%d", &option );
  }

  switch ( option ) {
  case 1:
    printf( "Random IP: " );
    print_ip( get_random_ip() );
    break;
  case 2:
    printf( "Random MAC: " );
    print_mac( get_random_mac() );
    break;
  case 3:
    get_ip_to_hex();
  }
}

/**
 * Generates a random *valid* IP address. The invalid IP addresses are
 * laid out in an array in the .c file.
 *
 * @param void.
 *
 * @return uint32_t random IP in decimal.
 */
static uint32_t
get_random_ip( void ) {
  while ( true ) {
    long ip = ( rand() & 0xff ) | ( ( rand() & 0xff ) << 8 ) | ( ( rand() & 0xff ) << 16 ) |
              ( ( rand() & 0xff ) << 24 );
    bool matches = false;
    for ( int i = 0; i < BAD_IP_SIZE; i++ ) {
      if ( ip == BAD_IP[i] ) {
        matches = true;
        break;
      }
    }

    if ( !matches ) {
      return ip;
    }
  }
}

/**
 * Generates a random MAC address.
 *
 * @param void.
 *
 * @return uint64_t 48-bit random mac address in decimal.
 */
static uint64_t
get_random_mac( void ) {
  uint8_t  byte_count = 6;
  uint64_t mac        = 0;
  for ( int i = 0; i < byte_count; i++ ) {
    uint64_t byte = ( uint64_t ) Stds_RandomInt( 0, 0xff );
    mac |= ( byte << ( i * BYTE ) );
  }

  return mac;
}

/**
 * Prompts the user to enter an IP address in the standard form. This is then converted
 * into an hex 32-bit integer, which is then printed with a leading 0x prefix so it can
 * be used in other pieces of the program.
 *
 * @param void.
 *
 * @return void.
 */
static void
get_ip_to_hex( void ) {
  strip_input();
  char buf[MAX_IP_BUFFER_SIZE];
  printf( "Enter your IP address in standard form (ex. xxx.xxx.xxx.xxx.): " );
  fgets( buf, sizeof( buf ), stdin );
  int32_t len  = strlen( buf );
  buf[len - 1] = '\0';
  printf( "IP in Hex: 0x%x.", ip_to_hex( buf, strlen( buf ) ) );
  printf( "\n" );
}