#include "../include/data_generation.h"

#define BAD_IP_SIZE 22

/**
 * Array of bad IP addresses. These are addresses
 * that cannot be generated by our function.
 */
static const uint32_t BAD_IP[BAD_IP_SIZE] = {
    0,          0x10000000, 0x64400000, 0x7f000000, 0xa9fe0000, 0xac100000, 0xc0000000, 0xc0000008,
    0xc0000009, 0xc00000aa, 0xc00000ab, 0xc0000200, 0xc01fc400, 0xc034c100, 0xc0586300, 0xc0a80000,
    0xc0af3000, 0xc6120000, 0xc6336400, 0xcb007100, 0xf0000000, 0xffffffff };

uint32_t
get_random_ip() {
  while (true) {
    long ip = rand() & 0xffffffff;
    bool matches = false;
    for (int i = 0; i < BAD_IP_SIZE; i++) {
      if (ip == BAD_IP[i]) {
        matches = true;
        break;
      }
    }

    if (!matches) {
      return ip;
    }
  }
}

uint64_t
get_random_mac() {
  uint8_t  nibble_count = 12;
  uint64_t mac          = 0;
  for ( int i = 0; i < nibble_count; i++ ) {
    uint8_t nibble = Stds_RandomInt( 0, 15 ) & 0xf;
    mac |= ( nibble << ( i * 4 ) );
  }

  return mac;
}
